feat: implement gerrit
bytebase/relay pull request #21
Opened 2022-12-27 03:36 UTC by ecmadao

2022-12-27 06:58 UTC, tianzhou reviewed
Let's update the README to add the gerrit hooker and bytebase sinker as well.

2022-12-27 06:58 UTC, tianzhou commented on hook/gerrit.go
> +	flag.StringVar(&gerritProject, "gerrit-project", "", "The Gerrit repository name")
change all project occurrence to repository?

![CleanShot 2022-12-27 at 14 52 12](https://user-images.githubusercontent.com/230323/209624536-d1aded63-32e7-4a49-a0aa-63e139d9b87e.png)

Though GerritChange API seems to pass "project", but I feel user are more familiar with the repository concept

2022-12-27 06:58 UTC, tianzhou commented on hook/gerrit.go
> +				httpCode: http.StatusInternalServerError,
sounds like a 400 bad request

2022-12-27 06:58 UTC, tianzhou commented on hook/gerrit.go
> +		log.Printf("gerrit event received: %s\n", message.Type)
remove log

2022-12-27 06:58 UTC, tianzhou commented on sink/bytebase.go
> +	flag.StringVar(&gerritUR, "gerrit-url", "https://gerrit.bytebase.com", "The Gerrit service URL")
gerritURL

2022-12-27 06:58 UTC, tianzhou commented on hook/gerrit.go
> +			log.Printf("ignore event as the branch or project doesn't match, expect %s:%s but got %s:%s", gerritProject, gerritProjectBranch, message.Change.Project, message.Change.Branch)
remove log

2022-12-27 06:58 UTC, tianzhou commented on sink/bytebase.go
> +		log.Printf("processing file %s\n", fileName)
remove log

2022-12-27 06:58 UTC, tianzhou commented on sink/bytebase.go
> +		log.Printf("start create issue %s\n", issueName)
remove log

2022-12-27 08:52 UTC, tianzhou requested changes

2022-12-27 08:52 UTC, tianzhou commented on README.md
> +#### `gerrit-branch`
```suggestion
#### `--gerrit-branch`
```

2022-12-27 08:52 UTC, tianzhou commented on README.md
> +The Gerrit service URL. We need to call the Gerrit service to list files in the change, and get the file content in the change.
I feel this should not be in the Bytebase part, instead it should be in the gerrit hooker side.

Otherwise, each sinker needs to have these flags.

2022-12-27 09:15 UTC, ecmadao commented on README.md
> +The Gerrit service URL. We need to call the Gerrit service to list files in the change, and get the file content in the change.
I feel it's also strange to put the `--gerrit-url` into gerrit hooker...or maybe add another part named "service"?

2022-12-28 01:21 UTC, ecmadao commented on README.md
> +The Bytebase sinker also depends on the Gerrit service. Check the docs below for the [Gerrit service](#gerrit-service).
WDYT @tianzhou

2022-12-28 05:20 UTC, tianzhou requested changes

2022-12-28 05:20 UTC, tianzhou commented on sink/bytebase.go
> +		content, err := sinker.gerritService.GetFileContent(c, p.Change.ID, p.PatchSet.Revision, fileName)
I feel this should be handled in the gerrit hooker, and the message passed to the sinker already has the changed files and their contents. Otherwise, each sinker needs to do this.

Of course, this is based on the assumption that sinkers always need the file content, and I feel that's a reasonable assumption.

2022-12-28 05:20 UTC, tianzhou commented on README.md
> +The Gerrit service URL. We need to call the Gerrit service to list files in the change, and get the file content in the change.
I guess we don't need this right now since we don't have a use case where multiple hookers/sinkers share a common service. It's simpler to co-locate relevant flags together.

If we do plan to add service module, the more likely ones are those horizontal modules like logging/monitoring services.

Please see another comment in sink/bytebase.go

2022-12-28 07:11 UTC, ecmadao commented on sink/bytebase.go
> +		content, err := sinker.gerritService.GetFileContent(c, p.Change.ID, p.PatchSet.Revision, fileName)
SGTM, updated

2022-12-28 07:18 UTC, tianzhou approved these changes
LGTM

2022-12-28 07:19 UTC, merged