refactor: abstract hooker and sinker interface
bytebase/relay pull request #9
Opened 2022-09-01 17:22 UTC by tianzhou

* Hooker registers the webhook handler at path `/foo`
* Sinker registers the webhook payload receiver at path `/foo`
* Configure external service foo to post webhook event to `/foo`

## Workflow

1. External service `foo` posts a webhook event to `/foo`
2. Hooker responds at `/foo`, extract the webhook payload, and performs some processing
3. Hooker sends the payload to Sinker registered at `/foo`

A specific case in this PR from GitHub webhook event to post messages to Lark group.

GitHub service webhook event -> GitHub Hooker -> Lark Sinker

2022-09-01 17:49 UTC, unknwon requested changes
Overall LGTM, request changes because I want to make sure we sort out some details.

2022-09-01 17:49 UTC, unknwon commented on cmd/root.go
> +		log.Fatalf("Failed to prepare hook: %v\n", err)
FYI, `log.Fatalf` (or any `log.XYZf` from stdlib) always prints to a new line, below is effectively the same
```suggestion
		log.Fatalf("Failed to prepare hook: %v", err)
```

2022-09-01 17:49 UTC, unknwon commented on hook/github.go
> +)
nit: they are two types of vars (regular vs. compile check), putting them into a single group doesn't feel great.

2022-09-01 17:49 UTC, unknwon commented on hook/github.go
> +}
Shouldn't this be called `githubHooker`? I'd imagine we'll have `gitlabHooker` for example.

2022-09-01 17:49 UTC, unknwon commented on hook/hook.go
> +	register(fs *flag.FlagSet, f *flamego.Flame, path string)
Please add some docstrings.

2022-09-01 17:49 UTC, unknwon commented on hook/hook.go
> +// Hooker is the interface for the webhook originator
```suggestion
// Hooker is the interface for the webhook originator.
```

2022-09-01 17:49 UTC, unknwon commented on hook/hook.go
> +// Prepare prepares all registered hooks before running (e.g. validate flags)
```suggestion
// Prepare prepares all registered hooks before running (e.g. validate flags).
```

2022-09-01 17:49 UTC, unknwon commented on payload/github.go
> +type GitHub struct {
```suggestion
type GitHubPushEvent struct {
```

2022-09-01 17:49 UTC, unknwon commented on sink/lark.go
> +}
Ditto
```suggestion
type larkSinker struct {
}
```

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +	send(c context.Context, path string, payload interface{}) error
Please add docstrings

2022-09-01 17:49 UTC, unknwon commented on hook/hook.go
> +	}
nit
```suggestion
	if h == nil {
		panic("hook: Register hooker is nil")
	}

	hooksMu.Lock()
	defer hooksMu.Unlock()
```

2022-09-01 17:49 UTC, unknwon commented on hook/hook.go
> +	hooks   = make(map[string]Hooker)
nit: My brain feels a bit split here
```suggestion
	hookersMu sync.RWMutex
	hookers   = make(map[string]Hooker)
```

WDYT?

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +	sinks   = make(map[string][]Sinker)
Ditto

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +
nit

```suggestion
	if s == nil {
		panic("sink: Register sinker is nil")
	}

	sinksMu.Lock()
	defer sinksMu.Unlock()
```

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +}
Pretty sure you can safely iterate over and append to a nil slice.

```suggestion
	for _, item := range sinks[path] {
		if item == s {
			panic("sink: Register called twice for sinker " + path)
		}
	}
	s.register(fs)
	sinks[path] = append(sinks[path], s)
}
```

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +func Send(c context.Context, path string, payload interface{}) error {
Please add docstring

2022-09-01 17:49 UTC, unknwon commented on sink/sink.go
> +// Prepare prepares all registered sinks before running (e.g. validate flags)
```suggestion
// Prepare prepares all registered sinks before running (e.g. validate flags).
```

2022-09-02 03:58 UTC, tianzhou reviewed
PTAL

2022-09-02 03:58 UTC, tianzhou commented on hook/github.go
> +}
this is already inside github.go

2022-09-02 03:58 UTC, tianzhou commented on sink/lark.go
> +}
this is already inside lark.go

2022-09-02 03:58 UTC, tianzhou commented on hook/github.go
> +)
Done

2022-09-02 03:58 UTC, tianzhou commented on sink/sink.go
> +	sinks   = make(map[string][]Sinker)
Done

2022-09-02 03:58 UTC, tianzhou commented on hook/hook.go
> +	register(fs *flag.FlagSet, f *flamego.Flame, path string)
Done

2022-09-02 04:00 UTC, tianzhou commented on cmd/root.go
> +		log.Fatalf("Failed to prepare hook: %v\n", err)
Done

2022-09-02 04:48 UTC, tianzhou commented on hook/github.go
> +}
Fixed

2022-09-02 04:50 UTC, unknwon approved these changes

2022-09-02 05:19 UTC, merged